apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - airflow-credentials-sealed.yaml
  - superset-credentials-sealed.yaml
  - trino-credentials-sealed.yaml
  - ionos-s3-credentials-sealed.yaml
