{{- $fullName := include "piveau-hub-ui.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "piveau-hub-ui.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: default
      protocol: TCP
  selector:
    {{- include "piveau-hub-ui.selectorLabels" . | nindent 4 }}
