apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - zookeeper.yaml
  - trino.yaml
  - opa.yaml
  - minio.yaml
  - postgres/postgres-helm-source.yaml
  - postgres/postgres-helm-release.yaml
    #  - superset.yaml
    #  - s3-connection.yaml
