# Default values for piveau.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  searchApiKey: mySearchApiKey
  repoApiKey: myRepoApiKey

tags:
  piveau-hub-repo: true
  piveau-hub-search: true
  piveau-hub-ui: true
  
piveau-hub-repo:
  ingress:
    enabled: true
  extraEnvs:
  # TODO: template in deployment env
  - name: PIVEAU_HUB_SEARCH_SERVICE
    value: "{\"enabled\":true,\"url\":\"stackable-piveau-hub-search\",\"port\":8080,\"api_key\":\"mySearchApiKey\"}"
  virtuoso:
    persistence:
      enabled: true
piveau-hub-search:
  imageTag: latest
  ingress:
    enabled: true
piveau-hub-ui:
  imageTag: latest  
  ingress:
    enabled: true