apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - opa.yaml
      #- zookeeper.yaml
    - hive-metastores.yaml
    - trino.yaml
    - trino-secrets.yaml
    - superset.yaml
    - airflow.yaml
    - piveau-helm.yaml
